version: "3.8"

volumes:
  db:
    name: db

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      mysql.localhost:
        condition: service_healthy
    links:
      - "mysql.localhost:database"

  mysql.localhost:
    image: mariadb
    hostname: db
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql:Z
      - ./sql:/docker-entrypoint-initdb.d:Z
    healthcheck:
      test: mariadb --password=$$DATABASE_PASSWORD -e 'show databases'
      interval: 30s
      timeout: 5s
      retries: 10
